### ISSUE TITLE
Issues with whitelist-based firewalls

### ISSUE THREAD

**Issue by morgothdidnothingwrong** [flamusdiu/python-pia#14]
Hello,

I came through several issues with python-pia through a firewall :
- some universities or dormitories (that's my user case, but I suppose some alike laws apply to a whole region too) block the git protocol, and I suggest you to move the sources of the Archlinux PKGBUILD to the https protocol,
- the same applies to the VPN handshakes : I can't connect to PIA, and I don't have the technical knowledge to build a conf file. I don't know which advantages the 1154 UDP port provides over TCP 443, but I'd suggest you to make at least one file to connect through HTTPS (TCP 443).

Thanks for your time, the Archlinux community is thankful.

**Comment by flamusdiu** [comment]
You can use the Advance configurations to change the protocol/port => https://wiki.archlinux.org/index.php/Private_Internet_Access_VPN#WIP:_Advanced_Options

There is an example configuration file there.

**Comment by flamusdiu** [comment]
As for the https problem, can you try to change this in the PKGBUILD and try rebuilding the package

```
 source=("https://www.privateinternetaccess.com/openvpn/openvpn.zip"
    "login-example.conf"
    "pia-example.conf"
    "restart.conf"
    "vpn.sh"
    "pia.8.gz"
    "hook.install"
    "hook.remove"
    "git://github.com/flamusdiu/python-pia.git#tag=v${pkgver}"
    "git://github.com/masterkorp/openvpn-update-resolv-conf.git"
    "update-resolv-conf.patch")
```

to

```
source=("https://www.privateinternetaccess.com/openvpn/openvpn.zip"
    "login-example.conf"
    "pia-example.conf"
    "restart.conf"
    "vpn.sh"
    "pia.8.gz"
    "hook.install"
    "hook.remove"
    "git+https://github.com/flamusdiu/python-pia.git#tag=v${pkgver}"
    "git+https://github.com/masterkorp/openvpn-update-resolv-conf.git"
    "update-resolv-conf.patch")
```

See if that fixes the pull at your university.

**Comment by flamusdiu** [comment]
@morgothdidnothingwrong any luck at testing the change above?

**Comment by flamusdiu** [comment]
went ahead and changed it. this is fixed.
