### ISSUE TITLE
ca and crl-verify point to the wrong file in openvpn config files

### ISSUE THREAD

**Issue by Oppzippy** [flamusdiu/python-pia#18]
Lines containing the issue:

```
crl-verify /etc/openvpn/crl.rsa.2096.pem
crl-ca /etc/openvpn/ca.rsa.2096.crt
```

This occurs in all of the openvpn conf files. crl.rsa.2096.pem and ca.rsa.2096.crt do not exist, and it is probably intended that these are supposed to be 2048, as that file does exist.

**Comment by Oppzippy** [comment]
Checked dev branch and it's already fixed. Can be ignored.

**Comment by flamusdiu** [comment]
yeah, I have epic typing skills. sorry about the confusion.
