### ISSUE TITLE
All .conf files in /etc/openvpn are using the wrong filenames for .pem and .crt

### ISSUE THREAD

**Issue by wrhight** [flamusdiu/python-pia#21]
The .conf files in /etc/openvpn referenced by "crl-verify" and "ca" are referencing "2096" for the .pem and .crt files. I suggest changing this to "2048" or "4096" for those using stronger encryption.

**Comment by wrhight** [comment]
Sorry. Just noticed this was closed and fixed for dev branch.

**Comment by flamusdiu** [comment]
@wrhight yeah, sorry. I am working on trying to get it pushed over. I only have my Razer Blade with me which I didn't get a chance to install Arch before I left.
