### ISSUE TITLE
Certificates are 2048 bits, but conf files look for 2096

### ISSUE THREAD

**Issue by ripdog** [flamusdiu/python-pia#23]
Brand new install on Arch, `pia -a` creates a bunch of config files which refer to a `ca.rsa.2096.crt`, which leads to this:

    /etc/openvpn/ca.rsa.2096.crt: cannot open `/etc/openvpn/ca.rsa.2096.crt' (No such file or directory)

Simply manually changing the conf files to refer to the 2048 versions fixes this.

Oh and the non -dev version on the AUR is broken, might wanna update it.

**Comment by flamusdiu** [comment]
That should be fixed! Which  version did you install?

**Comment by ripdog** [comment]
The -dev AUR package. I can get you a version number if you need it in 12 
hours.

**Comment by flamusdiu** [comment]
Can you test out https://aur.archlinux.org/packages/private-internet-access-vpn-dev/ for me? Should work. You'll need to run `pia -r` before you install this version, however. 

Apparently, I left some old code and "fixed" it the wrong location. Let me know if the dev version works for you.

**Comment by flamusdiu** [comment]
Fixed on dev branch. I'll push it over as soon as I get some more testing done with it. You can comment on #17 of you find problems with it.
