### ISSUE TITLE
Update for new openvpn

### ISSUE THREAD

**Issue by podiki** [flamusdiu/python-pia#24]
Upon updating `openvpn` the following message is displayed:

`This upgrade from openvpn 2.3.14-1 to openvpn 2.4.0-2 made changes that require
administrative interaction:`
` -> Configuration is expected in sub directories now. Move your files
    from /etc/openvpn/ to /etc/openvpn/server/ or /etc/openvpn/client/.`
 `-> The plugin lookup path changed, remove extra 'plugins/' from relative paths.`
 `-> The systemd unit openvpn@.service was replaced with openvpn-client@.service
    and openvpn-server@.service. Restart and reenable accordingly.`

Please update `python-pia` to follow these changes. Everything seems to still work as is, but better to follow the new conventions sooner rather than later. And thanks for the package, works great!

**Comment by flamusdiu** [comment]
Umm...thanks for pointing these out!

**Comment by podiki** [comment]
I should have noted this was on Arch. Just a heads up for now, as everything seems to work the same anyway.

**Comment by flamusdiu** [comment]
Yeah, still, going to push an update to fix it. Running `pia -a` won't work without manually coping the files if you are using OpenVPN directly.

**Comment by flamusdiu** [comment]
Can you test out https://aur.archlinux.org/packages/private-internet-access-vpn-dev/ for me? Should work. You'll need to run `pia -r` before you install this version, however.

**Comment by podiki** [comment]
I ran `pia -r` and then removed the non-dev version of this package (that is what I was using). Upon trying to install the dev version however, I ran into an error. Looks like a minor path issue. 

Here is the end of the output (via pacaur):
`==> Extracting sources...`
`  -> Creating working copy of python-pia git repo...`
`Reset branch 'makepkg'`
`  -> Creating working copy of openvpn-update-resolv-conf git repo...`
`Switched to a new branch 'makepkg'`
`==> Starting prepare()...`
`  -> Extracting Certifications...`
`  -> Extracting OpenVPN Configurations...`
`  -> Creating Remote Host List...`
`  -> Done.`
`==> Entering fakeroot environment...`
`==> Starting package()...`
`install: target '/home/john/.cache/pacaur/private-internet-access-vpn-dev/pkg/private-internet-access-vpn-dev/etc/openvpn/client' is not a directory`
`==> ERROR: A failure occurred in package().`
`    Aborting...`
`:: failed to build private-internet-access-vpn-dev package(s)`

**Comment by flamusdiu** [comment]
Woops. Fixed now.

**Comment by podiki** [comment]
That works for me. It didn't like trying to build with the cached directory from before (pacaur), but once I removed it so it could start fresh it worked fine. Running `pia -a` put config files in `/etc/openvpn/client`, so that looks good. Connecting with `sudo openvpn /etc/openvpn/client/SERVER.conf` works.

However, no VPN connections appear in NetworkManager (checked with a tray applet and `nmtui`) after restarting the NetworkManager service. Is that because NetworkManager isn't savvy yet to the new config locations for openvpn, or does this package need to update how it registers the configurations?

**Comment by flamusdiu** [comment]
Might be a different issue. NM stores configurations in `/etc/NetworkManager/system-connections` which are separate from OpenVPN's files.

**Comment by flamusdiu** [comment]
You should have configurations there when you run `pia -a` with both networkmanager and networkmanager-openvpn installed.

**Comment by podiki** [comment]
There are indeed connections in `/etc/NetworkManager/system-connections` after running `pia -a`, but they do not actually show up in networkmanager. I tried `pia -r` and removing the dev version and installing the non-dev version. After then running `pia -a` there are again files in `/etc/NetworkManager/system-connections` and they show up in networkmanager. Looks like something has changed then. Note though, that I was not running the dev version before, so maybe there was some other change between the versions as well?

**Comment by flamusdiu** [comment]
Not with that. Create a random VPN connection profile (or manually create one for PIA) and then see if it adds a file into that folder. I don't normally use NM.

**Comment by podiki** [comment]
Yes, NM does add a file into `/etc/NetworkManager/system-connections`. So for some reason, while both the dev and non-dev version of `private-internet-access-vpn` create files for NM, only the non-dev version has them actually show up in NM (with current version of openvpn and NM). Perhaps some difference in the PKGBUILD? I noticed there are slightly different permissions from the non-dev version.


Update: Yup, that's it. NetworkManger sees the config files if they have permissions of 600, not 640 as in the current dev version. I didn't look very closely at the code, but I guess this is because the NM files are copied/modified from the openvpn ones, which are installed with different permissions (and the network group) in the dev version?

**Comment by flamusdiu** [comment]
haha ... love security sometimes. Apparently, if they are not 600, NM treats them as insecure and won't load them. Thanks for the info.

**Comment by podiki** [comment]
Guess they don't want you using one where a non-root user could read your password, best to be safer.

Glad we got it all sorted out, thanks for the quick changes. All looks good to me now so I'll close this.

**Comment by flamusdiu** [comment]
@podiki I just pushed another change to fix #17 before I push it to the main branch. Can you test out dev again? Looks good for me but you never know.

**Comment by podiki** [comment]
Installation and usage through NetworkManger looks good to me!
