### ISSUE TITLE
NetworkManager files not being generated

### ISSUE THREAD

**Issue by vercruyce** [flamusdiu/python-pia#28]
I noticed that the configuration files for NetworkManager were not being generated. I tracked the possible problem down to the hooks.py file. The command binary for the NM strategy lists `/usr/lib/networkmanager/nm-openvpn-service`. If I look for this file on my system, it can be found in `/usr/lib/NetworkManager` (notice the camel case). I haven't found out if Network Manager has recently changed this path, because I never had this problem before.

ps: I also found a little indentation error in run.py r178, which printed "List of OpenVPN configurations" inside the previous loop.

**Comment by flamusdiu** [comment]
Ahh, that's possible. I usually use Connman. I saw some problems from the AUR site a about possible issues. I getting home today so I'll try and merge this and get it updated tomorrow. Thanks for noticing the issue.

PS: Dam spaces ... shoot them down! =P
