### ISSUE TITLE
Add option to change port?

### ISSUE THREAD

**Issue by martyla** [flamusdiu/python-pia#3]
It would be nice to allow changing the port, either through allowing customization of the base template, or an additional parameter.

"We support connections on a variety of ports, TCP 80/443/110, as well as a number of UDP ports: 53, 1194, 8080, 9201" - https://www.privateinternetaccess.com/forum/discussion/comment/5168/#Comment_5168

**Comment by flamusdiu** [comment]
I could add an opt in the config file. Though, would there be any reason to do this per host or just all hosts at the same time?

**Comment by martyla** [comment]
All hosts is probably reasonable...

The reason this option is desirable is when the default port of 1194 is blocked/inaccessible

**Comment by flamusdiu** [comment]
Okay, I'll add it in the next day or so

**Comment by flamusdiu** [comment]
Oops ... I was just working on this and realized ... I need to use both TCP and UDP configs. =P

**Comment by flamusdiu** [comment]
@martyla Are you using Network Manager? If so, can you setup a TCP connection and post the configuration (removing all private info)? I don't use it. =(

The default is UDP but I don't know what the file looks like if a TCP connection was setup in Network Manager to a VPN server. I can't find good info on it. =(

**Comment by flamusdiu** [comment]
@martyla just pushed an update -- should work with NM. Let me know if are any issues.

**Comment by martyla** [comment]
@flamusdiu Perfect, thanks!

I actually don't use Network Manager, just netctl + openvpn from systemctl.

My use case for this is to quickly generate the conf files in `/etc/openvpn`

**Comment by flamusdiu** [comment]
@martyla ahh, yeah, it works for that too. Let me know if there are any issues. I just use conman. =P

**Comment by flamusdiu** [comment]
@martyla did you get around to testing this?
