### ISSUE TITLE
Unable to specify host

### ISSUE THREAD

**Issue by chrisspen** [flamusdiu/python-pia#32]
How do you enable the VPN while specifying a specific host? Neither the docs nor wiki explain this, and seem to imply this package only generates configuration files, after which you just use OpenVPN manually to connect. Is this correct? I'm looking for a Python package to programmatically control PIA. Is that not the scope of this package?

**Comment by flamusdiu** [comment]
If you do nothing, it auto-generates configuration files for OpenVPN and (if installed) connman and networkmanger. See https://wiki.archlinux.org/index.php/Private_Internet_Access_VPN#Example_Configuration for how to set specific hosts.

**Comment by flamusdiu** [comment]
@chrisspen if you still have an issue with this, please let me know by reopening this issue.
