### ISSUE TITLE
Fails silently if dependencies not installed (esp. OpenVPN)

### ISSUE THREAD

**Issue by RunasSudo** [flamusdiu/python-pia#33]
For example, if `openvpn` is not installed, the `pia -a` command returns success, but does not create any configuration files. Investigating this behaviour is further masked by the fact that the Arch package creates the `/etc/openvpn` directory, making it seem as if OpenVPN is installed.

Since the OpenVPN configuration files are supposed to always be created, it seems illogical for the command to fail silently if this is not done.

Similarly, if `networkmanager-openvpn` is not installed, the command does not create the NetworkManager configuration files and again reports no error. This is more understandable, but perhaps a warning message might be in order that the NetworkManager configuration files will not be created because it is not installed.

**Comment by flamusdiu** [comment]
Umm, yeah, I'll have to change that. It looks for the binaries before deciding to create the files. I thought I had it to always do the OpenVPN config files.

**Comment by jonascj** [comment]
I see this behavior as well. Indeed `/etc/openvpn` exist without the openvpn-package installed, maybe some other weird package created it (connman, networkmanager, etc.), who knows ...

The arch package (https://aur.archlinux.org/packages/private-internet-access-vpn/) does not seem to install openvpn as a dependency (maybe you have it as an optional dependency?).

**Comment by flamusdiu** [comment]
Added dependency. I may have thought (at one point) that connman or nm was usable without OpenVPN installed which isn't the case.
