### ISSUE TITLE
[NM] pia.strong_encryption property is ignored

### ISSUE THREAD

**Issue by max-baz** [flamusdiu/python-pia#35]
We used to have the `strong_encryption` property under `[pia]` section in `pia.conf`, now it has no effect.

I found https://github.com/flamusdiu/python-pia/commit/73dc063b7cb5767f54a38ddefce6ab26ab389f6d, but I'm not sure anymore if removing the property was intentional, as I saw you referred to it on AUR a few months after that commit was made.

There is also no mention of this property on the wiki page.

**Comment by flamusdiu** [comment]
I thought I talked about it. It was removed because the port says if it's strong encryption or not. I will check the wiki.

**Comment by max-baz** [comment]
That makes sense, and it works! Thanks 🙂 It must have slipped my attention.

**Comment by flamusdiu** [comment]
Change due to #17 . I will need to update the Wiki to better explain it.
