### ISSUE TITLE
directory for systemd file is wrong

### ISSUE THREAD

**Issue by solsticedhiver** [flamusdiu/python-pia#36]
You have not fixed what I have already tell you in a comment the 2017-04-15 on AUR

There is a typo. Systemd files should be in /usr/lib/systemd/system not in /usr/lib/system/systemd

the patch to the PKGBUILD

    --- PKGBUILD	2016-10-16 02:39:08.000000000 +0200 
    +++ PKGBUILD.new	2017-04-05 23:39:35.878484391 +0200
    @@ -64,8 +64,8 @@
    package() {
    cd "${srcdir}"

    - install -D -m 644 restart.conf "${pkgdir}/usr/lib/system/openvpn@.service.d/restart.conf"
    - install -D -m 755 vpn.sh "${pkgdir}/usr/lib/system/systemd/system-sleep/vpn.sh"
    + install -D -m 644 restart.conf "${pkgdir}/usr/lib/systemd/openvpn@.service.d/restart.conf"
    + install -D -m 755 vpn.sh "${pkgdir}/usr/lib/systemd/system/system-sleep/vpn.sh"
    install -D -m 644 pia.8.gz "${pkgdir}/usr/share/man/man8/pia.8.gz"

**Comment by flamusdiu** [comment]
@solsticedhiver woops. I don't know how I missed that (and your post). I've been traveling for work and don't have Archlinux on my laptop (yet) sadly. Let me setup docker and get it fixed in the couple of days.

**Comment by flamusdiu** [comment]
fixed.

**Comment by solsticedhiver** [comment]
No.

    install -D -m 644 restart.conf "${pkgdir}/usr/lib/system/openvpn-client@.service.d/restart.conf"

It misses a d after system , again.

Did you actually test this package ? and those feature ?
