### ISSUE TITLE
ERROR: One or more files did not pass the validity check!

### ISSUE THREAD

**Issue by chipmunkboogie** [flamusdiu/python-pia#40]
AUR PACKAGE:

openvpn-ip-lport.zip ... FAILED
    openvpn.zip ... FAILED
    openvpn-strong.zip ... FAILED
    login-example.conf ... Passed
    pia-example.conf ... Passed
    restart.conf ... Passed
    vpn.sh ... Passed
    pia.8.gz ... Passed
    python-pia ... Skipped
    openvpn-update-resolv-conf ... Skipped

**Comment by flamusdiu** [comment]
Shoot...Let me check. I just updated last night.

**Comment by flamusdiu** [comment]
@chipmunkboogie check your version. I updated it to 3.3.3 rel 2 and doesn't look like the ZIPs changed between last night and today. If you are doing a direct pull, then make sure you re-pull it since I had an issue where the SRCINFO file had the incorrect hashes compared to the PKGBUILD file.

**Comment by chipmunkboogie** [comment]
I ran pacaur -Syu.  Aur does not list  an older version of the package. Full pull....?

**Comment by flamusdiu** [comment]
It might be the way `pacaur` pulls the updates. I use `aura`. I would do a full pull. Might want to look into how it caches the installs as well.

**Comment by allenkim** [comment]
I manually ran sha256sum on the packages and got the following, which was different from what I pulled.

```
04d6c427203f17b22a524772ae940be58a9f38a88518a36bc971d3ba6951f50c  openvpn-ip-lport.zip
827a7a60bb3a9124b8738da706dfefbd28b0cb34632be40a84c52462d760ddf7  openvpn.zip
ee525ada8913a80c169c3c1f4fccd44fef7c7214f2bd4a6b4b613e8b0b1a2dac  openvpn-strong.zip
```

Here was what I pulled correspondingly.
```
'702abfd524d622832294d39425ce28dc2f92cd60804cd376ca87e8719767fcf9'
'8589aefbc0db55d57f9e7ea43f5ce5676f987f86abf05fd93b9c8adedb8d24e5'
'1d25015b279706a7a47000393d0b9606b985dc5dc892ac8e8088c0aa6c9339c9'
```

**Comment by flamusdiu** [comment]
@allenkim I updated the zips again. I am working on trying to do a continuous build to help with these zips updating so much.

**Comment by Bradley-Kars** [comment]
Its happening again sadly

==> Validating source files with sha256sums...
    ip-lport-3.3.3-5.zip ... FAILED
    default-3.3.3-5.zip ... FAILED
    strong-3.3.3-5.zip ... FAILED
    login-example.conf ... Passed
    pia-example.conf ... Passed
    restart.conf ... Passed
    vpn.sh ... Passed
    pia.8.gz ... Passed
    python-pia ... Skipped
    openvpn-update-resolv-conf ... Skipped
==> ERROR: One or more files did not pass the validity check!
==> ERROR: Makepkg was unable to build private-internet-access-vpn.

**Comment by Bradley-Kars** [comment]
and when using aura:

aura >>= Fetching package information...
aura >>= Comparing package versions...                                                                                                                                 
aura >>= No AUR package upgrades necessary.
aura >>= `private-internet-access-vpn` PKGBUILD is up to date.
aura >>= Determining dependencies...                                                                                                                                   
aura >>= AUR Packages:                                                                                                                                                 
private-internet-access-vpn

aura >>= Continue? [Y/n] 
aura >>= Building `private-internet-access-vpn`...
aura >>= Well, building `private-internet-access-vpn` failed.
aura >>= Dumping makepkg output in 3.. 2.. 1..
==> Making package: private-internet-access-vpn 3.3.3-5 (Wed Apr 11 20:06:58 CDT 2018)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading ip-lport-3.3.3-5.zip...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16170  100 16170    0     0  40730      0 --:--:-- --:--:-- --:--:-- 40730
  -> Downloading default-3.3.3-5.zip...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17521  100 17521    0     0  40841      0 --:--:-- --:--:-- --:--:-- 40841
  -> Downloading strong-3.3.3-5.zip...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18379  100 18379    0     0  52213      0 --:--:-- --:--:-- --:--:-- 52213
  -> Found login-example.conf
  -> Found pia-example.conf
  -> Found restart.conf
  -> Found vpn.sh
  -> Found pia.8.gz
  -> Cloning python-pia git repo...
Cloning into bare repository '/var/cache/pacman/pkg/private-internet-access-vpn15421/private-internet-access-vpn/python-pia'...
  -> Cloning openvpn-update-resolv-conf git repo...
Cloning into bare repository '/var/cache/pacman/pkg/private-internet-access-vpn15421/private-internet-access-vpn/openvpn-update-resolv-conf'...
==> Validating source files with sha256sums...
    ip-lport-3.3.3-5.zip ... FAILED
    default-3.3.3-5.zip ... FAILED
    strong-3.3.3-5.zip ... FAILED
    login-example.conf ... Passed
    pia-example.conf ... Passed
    restart.conf ... Passed
    vpn.sh ... Passed
    pia.8.gz ... Passed
    python-pia ... Skipped
    openvpn-update-resolv-conf ... Skipped
==> ERROR: One or more files did not pass the validity check!

**Comment by Ralph-Fonz** [comment]
New SHA sums:

sha256sums=('68de7ba3c2a3ce1a720af9ec33a36a1e07ce60fcd9d61c49dd6f098f958cffd2' '2f0571f19c3546cd0dea9aab0c99ba6a540d02e900bb006b0c28c1a1594b85be' '6cb0b0e4f424d7c2e0787a7dab344266d51931fdb310c0e6dd75e4ea33ed5008' '4322a2a4bc3e206c6ab7e1df87a8805032b76c177c1ed9dd3501260ed32ccb30' '797dbdb6e3aadc86f97262e26d61cf4847caf85dda4b7a97cac59088cb912b27' '246fc4dc3218f56b4c70014df6801b10fc2a573d6545962b7fce05f16908c54e' '7f4a5ee1fb8ea4d0e69ed2a8217c575cf335f21e90082f6e423c769eca4a7a46' 'dd15ff9d020d6779c51bff560c8571b462cc7ca3f4d2a92b8103056be4b2e0fd' 'SKIP' 'SKIP')
