### ISSUE TITLE
Check sums are completely out of date

### ISSUE THREAD

**Issue by j3r1ch0** [flamusdiu/python-pia#45]
Hi, this seems to be unable to be installed both from the AUR package (checksums are out of date) and also through doing a git clone of this repo and running the ez_setup.py script.

**Comment by smackert** [comment]
Ran into this issue just now as well! You can skip the checksum validation by replacing the hashes in PKGBUILD with SKIP.

`sha256sums=('SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP')`

Keep in mind, this is really really bad practice.

**Comment by j3r1ch0** [comment]
> Ran into this issue just now as well! You can skip the checksum validation by replacing the hashes in PKGBUILD with SKIP.
> 
> `sha256sums=('SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP')`
> 
> Keep in mind, this is really really bad practice.

Luckily I found another way, and just got it all setup through NetworkManager and the vpn applet. I wasn't really comfortable with skipping hash verification. Thanks though!

**Comment by flamusdiu** [comment]
Yeah, I will update the next few days

**Comment by slch** [comment]
Yeaaa

**Comment by FryDay** [comment]
Is this going to get updated?

**Comment by sebiimaks** [comment]
The answer to that question should be obvious.

**Comment by j3r1ch0** [comment]
>Is this going to get updated?

@FryDay I really doubt it at this point

**Comment by aronwk-aaron** [comment]
> Yeah, I will update the next few days


See #40 #41 #42 
@flamusdiu

**Comment by flamusdiu** [comment]
Fixed with https://github.com/flamusdiu/python-pia/releases/tag/v3.4
