### ISSUE TITLE
Traceback error pia -a and pia -r

### ISSUE THREAD

**Issue by E1lsum** [flamusdiu/python-pia#47]
Hi I am getting this rror when running pia -a or pia -r
`Traceback (most recent call last):
  File "/usr/bin/pia", line 33, in <module>
    sys.exit(load_entry_point('pia==3.4', 'console_scripts', 'pia')())
  File "/usr/lib/python3.9/site-packages/pia/command_line.py", line 23, in main
    pia.run.run()
  File "/usr/lib/python3.9/site-packages/pia/run.py", line 53, in run
    properties.parse_conf_file()
  File "/usr/lib/python3.9/site-packages/pia/conf/properties.py", line 237, in parse_conf_file
    props.port = getattr(configure_section, "port", [props.default_port])[0]
  File "/usr/lib/python3.9/site-packages/pia/conf/properties.py", line 124, in port
    config = self._config_lookup[self._port_lookup[value]['config']]
KeyError: '80'`
Any ideas on a fix?
Python --version = 3.9.4
PIA --version = 3.3.2
private-internet-access-vpn installed by yay

**Comment by flamusdiu** [comment]
Let me take a look ... what config are you using?

**Comment by E1lsum** [comment]
In pia.conf
`openvpn_auto_login = False

[configure]
apps = nm
hosts = US East, US West, Japan, UK London
port = 80`

Pretty much default until I get used to it, and I have sent user name and password in login.conf.  Just the two lines as specified.

**Comment by flamusdiu** [comment]
Yeah, I had to remove port 80. See: https://www.privateinternetaccess.com/helpdesk/kb/articles/which-encryption-auth-settings-should-i-use-for-ports-on-your-gateways-3

Unless you use the official client. port 80 doesn't work. At least according to this article.

**Comment by E1lsum** [comment]
Thanks for that, didn't consider that could be the issue :smile:

**Comment by flamusdiu** [comment]
No worries. I wish it worked but they changed it. =\
