### ISSUE TITLE
spaces in hosts in pia.conf breaks "pia -a"

### ISSUE THREAD

**Issue by ghost** [flamusdiu/python-pia#5]
```
[configure]
apps = openvpn, nm
```

breaks the application, whereas

```
[configure]
apps = openvpn,nm
```

works fine

**Comment by ghost** [comment]
This introduced a new bug that now you have to use "US_East" instead of the mentioned "US East", since you remove the blanks: https://gist.github.com/torpet/b2c92f17e2070fbe3fdcdab36f2206de

**Comment by flamusdiu** [comment]
Yeah, I noticed that. I need to fix that up before my OCD kills me. =P
