### ISSUE TITLE
NetworkManager does not work with new `openvpn.zip`

### ISSUE THREAD

**Issue by vise890** [flamusdiu/python-pia#9]
When I
1. follow the [wiki](https://wiki.archlinux.org/index.php/Private_Internet_Access_VPN) and I change the `PKGBUILD` to point to the new [`openvpn.zip` from PIA](https://www.privateinternetaccess.com/openvpn/openvpn.zip)
2. run `pia -a`
3. try to connect to a VPN through NetworkManager

Then:
- I get a notification "connection failed"
- I see this in `journalctl`:
  `Jul 12 21:07:30 [..]: Options error: --ca fails with '/etc/openvpn/ca.crt': No such file or directory`
## Possible solutions

I think [the `NetworkManager` template](https://github.com/flamusdiu/python-pia/blob/master/src/pia/applications/template-configs/nm.cfg#L16) should point to `ca.rsa.2048.crt`

Also I set `proto-tcp=yes` and `port=502` as described by nigeil in [the AUR comment](https://aur.archlinux.org/packages/private-internet-access-vpn/) and added `cipher=AES-128-CBC`

The _working_ NM config I have now is:

```
[connection]
id=UK Southampton
uuid=********************************
type=vpn

[vpn]
service-type=org.freedesktop.NetworkManager.openvpn
connection-type=password
password-flags=0
remote=uk-southampton.privateinternetaccess.com
comp-lzo=yes
reneg-seconds=0
port=502
username=**********
remote-cert-tls=server
ca=/etc/openvpn/ca.rsa.2048.crt
dev=tun
cipher=AES-128-CBC
proto-tcp=yes

[ipv6]
method=auto

[ipv4]
method=auto

[vpn-secrets]
password=**********

```

EDIT: added info, it's now working

**Comment by flamusdiu** [comment]
Yeah, this is due to new security requirements. I just noticed these changes last night.

**Comment by flamusdiu** [comment]
Fixed with v2.8

Umm, just curious why you put the login information directly into the file?

**Comment by vise890** [comment]
It's just the compiled version of the [nm template](https://github.com/flamusdiu/python-pia/blob/master/src/pia/applications/template-configs/nm.cfg#L16)

**Comment by flamusdiu** [comment]
Lol...wow, not enough coffee. =p
